const networks = [
  { name: 'aptos', image: 'aptos.svg', url: '' },
  { name: 'arbitrum', image: 'arbitrum.svg', url: '' },
  { name: 'astar', image: 'astar.svg', url: '' },
  { name: 'aurora', image: 'aurora.svg', url: '' },
  { name: 'avalanche', image: 'avalanche.svg', url: '' },
  { name: 'base', image: 'base.png', url: '' },
  { name: 'bnb chain', image: 'bnb-chain.svg', url: '' },
  { name: 'boba', image: 'boba.svg', url: '' },
  { name: 'canto', image: 'canto.png', url: '' },
  { name: 'celo', image: 'celo.svg', url: '' },
  { name: 'cronos', image: 'cronos.svg', url: '' },
  { name: 'dfk chain', image: 'dfk-chain.svg', url: '' },
  { name: 'doge chain', image: 'doge-chain.svg', url: '' },
  { name: 'dojima', image: 'dojima.svg', url: '' },
  { name: 'ethereum', image: 'ethereum.svg', url: '' },
  { name: 'evmos', image: 'evmos.svg', url: '' },
  { name: 'fantom', image: 'fantom.svg', url: '' },
  { name: 'fuel network', image: 'fuel-network.png', url: '' },
  { name: 'function x', image: 'function-x.svg', url: '' },
  { name: 'fuse', image: 'fuse.svg', url: '' },
  { name: 'gnosis chain', image: 'gnosis-chain.svg', url: '' },
  { name: 'iotex', image: 'iotex.svg', url: '' },
  { name: 'kardia chain', image: 'kardia-chain.svg', url: '' },
  { name: 'kava', image: 'kava.svg', url: '' },
  { name: 'klaytn', image: 'klaytn.svg', url: '' },
  { name: 'mantle', image: 'mantle.svg', url: '' },
  { name: 'metis', image: 'metis.svg', url: '' },
  { name: 'milkomeda', image: 'milkomeda.svg', url: '' },
  { name: 'moonbeam', image: 'moonbeam.svg', url: '' },
  { name: 'optimism', image: 'optimism.svg', url: '' },
  { name: 'polygon', image: 'polygon.svg', url: '' },
  { name: 'rollux', image: 'rollux.svg', url: '' },
  { name: 'rootstock', image: 'rootstock.png', url: '' },
  { name: 'scroll', image: 'scroll.png', url: '' },
  { name: 'shardem', image: 'shardem.svg', url: '' },
  { name: 'starknet', image: 'starknet.png', url: '' },
  { name: 'sui', image: 'sui.svg', url: '' },
  { name: 'syscoin', image: 'syscoin.svg', url: '' },
  { name: 'telos', image: 'telos.svg', url: '' },
  { name: 'tomochain', image: 'tomochain.svg', url: '' },
  { name: 'ton', image: 'ton.png', url: '' },
  { name: 'watr', image: 'watr.svg', url: '' },
  { name: 'zk sync', image: 'zk-sync.png', url: '' },
]

export default networks
