const providers = [
  { name: '4sv', image: '4sv.png', url: '' },
  { name: 'balancer', image: 'balancer.png', url: '' },
  { name: 'binance us', image: 'binance-us.svg', url: '' },
  { name: 'binance', image: 'binance.svg', url: '' },
  { name: 'bitstamp', image: 'bitstamp.svg', url: '' },
  { name: 'bittrex', image: 'bittrex.png', url: '' },
  { name: 'bybit', image: 'bybit.svg', url: '' },
  { name: 'camelot', image: 'camelot.png', url: '' },
  { name: 'coinbase', image: 'coinbase.svg', url: '' },
  { name: 'coingecko', image: 'coingecko.png', url: '' },
  { name: 'coinlist', image: 'coinlist.svg', url: '' },
  { name: 'coinmarketcap', image: 'coinmarketcap.png', url: '' },
  { name: 'crypto', image: 'crypto.svg', url: '' },
  { name: 'curve', image: 'curve.png', url: '' },
  { name: 'ecb', image: 'ecb.png', url: '' },
  { name: 'gateio', image: 'gateio.svg', url: '' },
  { name: 'gemini', image: 'gemini.svg', url: '' },
  { name: 'huobi', image: 'huobi.svg', url: '' },
  { name: 'kaiko', image: 'kaiko.svg', url: '' },
  { name: 'kraken', image: 'kraken.svg', url: '' },
  { name: 'kucoin', image: 'kucoin.svg', url: '' },
  { name: 'lens', image: 'lens.png', url: '' },
  { name: 'mexc', image: 'mexc.svg', url: '' },
  { name: 'okcoin', image: 'okcoin.svg', url: '' },
  { name: 'okx', image: 'okx.svg', url: '' },
  { name: 'pancake', image: 'pancake.svg', url: '' },
  { name: 'pangolin', image: 'pangolin.png', url: '' },
  { name: 'poloniex', image: 'poloniex.svg', url: '' },
  { name: 'sushiswap', image: 'sushiswap.png', url: '' },
  { name: 'traderjoe', image: 'traderjoe.png', url: '' },
  { name: 'twelve data', image: 'twelve-data.png', url: '' },
  { name: 'uniswap', image: 'uniswap.png', url: '' },
  { name: 'yahoo finance', image: 'yahoo-finance.png', url: '' },
]

export default providers
